# Generated by Django 5.0.7 on 2024-10-12 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='clientes',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='pedidos.cliente'),
        ),
    ]
