# Generated by Django 5.0.7 on 2024-10-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_clientes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acompanamiento',
            name='Plato',
        ),
        migrations.AddField(
            model_name='plato',
            name='acompanamientos',
            field=models.ManyToManyField(related_name='platos', to='pedidos.acompanamiento'),
        ),
    ]
