# Generated by Django 5.0.7 on 2024-10-12 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_remove_acompanamiento_plato_plato_acompanamientos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acompanamiento',
            name='precio',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.PositiveIntegerField(),
        ),
    ]
