# Generated by Django 5.0.7 on 2024-10-12 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_alter_acompanamiento_precio_alter_pedido_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='precio',
            field=models.PositiveIntegerField(),
        ),
    ]
