# Generated by Django 5.0.7 on 2024-10-12 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_alter_plato_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='identificacion',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
